# Generated by Django 4.2.1 on 2023-05-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_blog_created_at_blog_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='extra_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
