# Generated by Django 4.2.1 on 2023-05-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_blog_extra_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(choices=[('TECH', 'TECH'), ('Django', 'Django'), ('React', 'React'), ('jobs', 'Jobs')], default='TECH', max_length=100),
        ),
    ]
